<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 4px;
            text-align: left;
        }

        th {
            background: #428bca;
            color: #fff;
        }

        .title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin-top: 10px;
        }

        .meta {
            text-align: center;
            font-size: 10px;
            margin-top: 4px;
        }
    </style>
</head>

<body>
    <div class="title">{{ $title }}</div>
    <div class="meta">Generated on: {{ $generatedOn }}</div>
    <table>
        <thead>
            <tr>
                @foreach(array_keys($rows->first()) as $col)
                <th>{{ $col }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr style=`background: {{ stripos($row['Status'],'Absent')!==false || stripos($row['Status'],'Leave')!==false ? '#FFEBEE':'transparent' }}; color: {{ stripos($row['Status'],'Absent')!==false||stripos($row['Status'],'Leave')!==false? '#D32F2F':'#000' }};`>
                @foreach($row as $cell)
                <td>{{ $cell }}</td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    <div style="position:fixed;bottom:10px;font-size:8px;width:100%;display:flex;justify-content:space-between;">
        <div>Generated by Aero Enterprise Suite</div>
        <div>Page <span class="page"></span></div>
    </div>
    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_text(550, 820, "Page {PAGE_NUM} of {PAGE_COUNT}", 'helvetica', 8, array(0,0,0));
        }
    </script>
</body>

</html>