@echo off
REM XAMPP Configuration Helper for Aero-HR Multi-Tenant Setup
REM Run this as Administrator

echo ================================================
echo    Aero-HR XAMPP Configuration Helper
echo ================================================
echo.

REM Check if running as administrator
net session >nul 2>&1
if %errorLevel% NEQ 0 (
    echo ❌ ERROR: This script must be run as Administrator
    echo    Right-click and select "Run as administrator"
    pause
    exit /b 1
)

echo ✅ Running as Administrator
echo.

REM Backup existing hosts file
echo 📁 Backing up hosts file...
copy "C:\Windows\System32\drivers\etc\hosts" "C:\Windows\System32\drivers\etc\hosts.backup.%date:~-4,4%%date:~-10,2%%date:~-7,2%" >nul 2>&1
echo ✅ Hosts file backed up
echo.

REM Add domains to hosts file
echo 🌐 Adding local domains to hosts file...
echo # Aero-HR Multi-Tenant Local Domains - Added %date% %time% >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    dbedc.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    acme.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    techstart.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    globalhr.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    innovate.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo 127.0.0.1    test.aero-hr.local >> "C:\Windows\System32\drivers\etc\hosts"
echo # End Aero-HR domains >> "C:\Windows\System32\drivers\etc\hosts"
echo.

echo ✅ Domains added to hosts file:
echo    - aero-hr.local (Central/Admin)
echo    - dbedc.aero-hr.local
echo    - acme.aero-hr.local  
echo    - techstart.aero-hr.local
echo    - globalhr.aero-hr.local
echo    - innovate.aero-hr.local
echo    - test.aero-hr.local
echo.

REM Flush DNS cache
echo 🔄 Flushing DNS cache...
ipconfig /flushdns >nul 2>&1
echo ✅ DNS cache flushed
echo.

REM Check if XAMPP is installed
set "XAMPP_PATH=C:\xampp"
if not exist "%XAMPP_PATH%" (
    echo ❌ XAMPP not found at %XAMPP_PATH%
    echo    Please install XAMPP or update the path in this script
    pause
    exit /b 1
)

echo ✅ XAMPP found at %XAMPP_PATH%
echo.

REM Create virtual hosts configuration
echo 📝 Creating virtual hosts configuration...
(
echo # Virtual Hosts Configuration for Aero-HR Multi-Tenant
echo # Generated by setup script on %date% %time%
echo.
echo # Main Central Domain ^(SaaS Admin^)
echo ^<VirtualHost *:80^>
echo     ServerName aero-hr.local
echo     DocumentRoot "D:/Repos/Aero-HR/public"
echo     ErrorLog "logs/aero-hr-error.log"
echo     CustomLog "logs/aero-hr-access.log" common
echo.    
echo     ^<Directory "D:/Repos/Aero-HR/public"^>
echo         AllowOverride All
echo         Require all granted
echo         DirectoryIndex index.php
echo     ^</Directory^>
echo.    
echo     SetEnv APP_ENV local
echo     SetEnv APP_DEBUG true
echo ^</VirtualHost^>
echo.
echo # Tenant Subdomains ^(Wildcard^)
echo ^<VirtualHost *:80^>
echo     ServerAlias *.aero-hr.local
echo     DocumentRoot "D:/Repos/Aero-HR/public"
echo     ErrorLog "logs/aero-hr-tenant-error.log"
echo     CustomLog "logs/aero-hr-tenant-access.log" common
echo.    
echo     ^<Directory "D:/Repos/Aero-HR/public"^>
echo         AllowOverride All
echo         Require all granted
echo         DirectoryIndex index.php
echo     ^</Directory^>
echo.    
echo     SetEnv APP_ENV local
echo     SetEnv APP_DEBUG true
echo ^</VirtualHost^>
) > "%XAMPP_PATH%\apache\conf\extra\httpd-vhosts.conf"

echo ✅ Virtual hosts configuration created
echo.

REM Check if virtual hosts are enabled in httpd.conf
findstr /C:"Include conf/extra/httpd-vhosts.conf" "%XAMPP_PATH%\apache\conf\httpd.conf" >nul 2>&1
if %errorLevel% NEQ 0 (
    echo 🔧 Enabling virtual hosts in httpd.conf...
    echo Include conf/extra/httpd-vhosts.conf >> "%XAMPP_PATH%\apache\conf\httpd.conf"
    echo ✅ Virtual hosts enabled
) else (
    echo ✅ Virtual hosts already enabled in httpd.conf
)
echo.

echo ================================================
echo    Configuration Complete!
echo ================================================
echo.
echo 📋 Next Steps:
echo 1. Start XAMPP Apache and MySQL services
echo 2. Navigate to your project: cd D:\Repos\Aero-HR
echo 3. Run: php create_xampp_tenants.php
echo 4. Configure your .env file for local domains
echo 5. Test: http://aero-hr.local
echo.
echo 🌐 Available URLs after setup:
echo    Central Admin: http://aero-hr.local
echo    Login: http://aero-hr.local/login
echo    Tenant Example: http://dbedc.aero-hr.local/login
echo.
echo 📚 For detailed instructions, see: docs/xampp-setup-guide.md
echo.
pause
